/**:
  ros__parameters:
    # marker_size
    marker_size: 0.6

    # target_tag_ids
    target_tag_ids: ['0','4','5']

    # covariance
    covariance: [0.1, 0.0, 0.0, 0.0,  0.0,  0.0,
                 0.0, 0.1, 0.0, 0.0,  0.0,  0.0,
                 0.0, 0.0, 0.1, 0.0,  0.0,  0.0,
                 0.0, 0.0, 0.0, 0.01, 0.0,  0.0,
                 0.0, 0.0, 0.0, 0.0,  0.01, 0.0,
                 0.0, 0.0, 0.0, 0.0,  0.0,  0.01]

    # Detect AR-Tags within this range and publish the pose of ego vehicle
    distance_threshold: 6.0  # [m]

    # Camera frame id
    camera_frame: "camera"

    # Detector parameters
    # See https://github.com/pal-robotics/aruco_ros/blob/7787a6794d30c248bc546d1582e65dd47bc40c12/aruco/include/aruco/markerdetector.h#L106-L126
    detection_mode: "DM_NORMAL"  # select from [DM_NORMAL, DM_FAST, DM_VIDEO_FAST]
    min_marker_size: 0.02
